version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=BankingApp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass RedisPassword
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    external: false
  redis-data:
    external: false